# Generated by Django 5.2.4 on 2025-07-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_category_remove_post_creted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='exerpt',
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
